AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Aconite: CFN Template to create am IAM Role for Lambda Function

Metadata:
  TemplateName: iam-role-stack.yaml
  TemplateType: IAM Role / IAM Policy
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Aconite
  Modification History:
    - 1.0.0  - Oct 20, 2023   -- Initial Version 
  Resources: 
    - IAM Role
    - IAM Policy Attached To The Role
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: 'Project And Environment:'
      Parameters: 
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
      - StackName
    #################################### KMS Key ###################################################
    - Label: 
        default: 'KMS Configuration:'
      Parameters: 
      - KmsMasterKeyId
    #################################### SNS Topic #################################################
    - Label: 
        default: "SNS Configuration"
      Parameters: 
      - SNSTopicBaseName
    #################################### State Machine #############################################
    - Label: 
        default: "Step Function configuration"
      Parameters:
      - StepFunctionBaseName
      - StepFunctionExecutionRoleBaseName
      - StepFunctionExecutionPolicyBaseName
    ParameterLabels:
      ########################################### Project Name and Environment #######################
      ProjectName:
        default: 'Project Name.'
      Environment:
        default: 'Environment Name.'
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref"
      GitHubURL: 
        default: "GitHub repository URL"
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA: 
        default: "GitHub Workflow Run Number."
      GitHubRepository:
        default: "GitHub repository name."
      CiBuild:
        default: "Feature branch Ci Build"
      ################################## SNS #######################################################
      SNSTopicBaseName:
        default: "Result Notification SQS Topic Name."
      #################################### State Machine ###########################################
      StepFunctionBaseName:
        default: "The base name of the state machine."
      StepFunctionExecutionRoleBaseName:
        default: "The base name of the State Machine execution Role."
      StepFunctionExecutionPolicyBaseName: 
        default: "The base name of the State Machine execution Policy."
Parameters:
  ################## Project Name and Environment ##################################################
  ProjectName:
    Default: tarius
    Description: 'The Project Name.'
    Type: String
    MinLength: 4
    MaxLength: 30
    AllowedPattern: '[a-z]*'
    ConstraintDescription: 'The length should be between 5 and 30, must contain only lowercase alphabets.'
  Environment:
    Default: devl
    Description: 'The Environment Name.'
    Type: String
    AllowedValues: ['devl', 'test', 'prod']
    ConstraintDescription: 'The Environment must be devl / test or prod'
 #################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  StackName:
    Default: ""
    Description: "The name of the stack which created the resource"
    Type: String
  ###################################### KMS #######################################################
  KmsMasterKeyId:
    Default: "arn:aws:kms:us-east-1:237376087602:key/f7eb118d-f1d2-4d70-a046-dfada470840e"
    Description: "The KMS Key Id Used For Encryption."
    Type: String
    MinLength: 75
    MaxLength: 75
    AllowedPattern: "[a-z:/0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."  
  ###################################### SNS ####################################################### 
  SNSTopicBaseName:
    Default: "sns-topic"
    Description: The Base Name of the SNS Topic.
    Type: String
    MinLength: 9
    MaxLength: 50
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: The length should be between 10 and 50, must contain only lowercase letter,numbers,dash, dot and should start with a letter.
  ###################################### Step Function #############################################
  StepFunctionBaseName:
    Default: step-function
    Description: The base name of the step function
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: '[a-zA-Z0-9-]*'
    ConstraintDescription: The length should be between 5 and 10, must contain only alphanumeric or dash.
  StepFunctionExecutionRoleBaseName:
    Default: sf-execution-role
    Description: Lambda Function Execution Role Name
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: '[a-zA-Z0-9-]*'
    ConstraintDescription: The length should be between 5 and 10, must contain only alphanumeric or dash.
  StepFunctionExecutionPolicyBaseName:
    Default: sf-execution-policy
    Description: Lambda Function Execution Policy Name
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: '[a-zA-Z0-9-]*'
    ConstraintDescription: The length should be between 5 and 15, must contain only alphanumeric or dash.
Resources:
  ################################ State Machine Execution Role #################################
  StepFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${StepFunctionExecutionRoleBaseName}-${Environment}${CiBuild}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - !Sub 'states.${AWS::Region}.amazonaws.com'
          Action:
          - sts:AssumeRole
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
      Policies:
        - PolicyName: !Sub '${ProjectName}-${StepFunctionExecutionPolicyBaseName}-${Environment}${CiBuild}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowLogDelivery
              Effect: Allow
              Action: 
              - logs:CreateLogDelivery
              - logs:GetLogDelivery
              - logs:UpdateLogDelivery
              - logs:DeleteLogDelivery
              - logs:ListLogDeliveries
              - logs:PutResourcePolicy
              - logs:DescribeResourcePolicies
              - logs:DescribeLogGroups
              Resource: '*'
            - Sid: AllowLogDestination
              Effect: Allow
              Action:
              - logs:PutDestination
              - logs:PutDestinationPolicy
              - logs:PutLogEvents
              - logs:CreateLogGroup
              - logs:CreateLogStream
              Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/states/${ProjectName}-${StepFunctionBaseName}-${Environment}-${AWS::Region}${CiBuild}:*'
            - Sid: AllowSNSPublishMessage
              Effect: Allow
              Action: 
                - sns:Publish
              Resource: !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-${SNSTopicBaseName}-${Environment}-${AWS::Region}${CiBuild}'
            - Sid: AllowKMSDecrypt
              Effect: Allow
              Action: 
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:GenerateDataKeyPair
              Resource: !Ref KmsMasterKeyId
            - Sid: AllowECSRunTask
              Effect: Allow
              Action:
              - 'ecs:*'
              Resource: '*'
      Tags:
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: EnvironmentName
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
      - Key: StackName
        Value: !Ref StackName
Outputs:
  StepFunctionExecutionRoleArn:
    Description: The Arn of the Step Function Execution Role
    Value: !GetAtt StepFunctionExecutionRole.Arn