AWSTemplateFormatVersion: '2010-09-09'
Description: >-
   Project Clover: Root Stack Template to create a State Machine and associated services and IAM role to manage a container task (Amazon ECS, Amazon SNS)

Metadata:
  TemplateName: clover-root-stack.yaml
  TemplateType: Root Stack
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Clover
  Modification History:
    - 1.0.0  - Oct 25, 2023   -- Initial Version
  Resources: 
    - Resources
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label:
        default: "Project Name And Environment:"
      Parameters:
      - ProjectName
      - Environment
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyAlias
      - KmsMasterKeyId
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
      - StackName
    #################################### Code Repository Bucket ####################################
    - Label:
        default: "Code Repository S3 Bucket:"
      Parameters:
      - CodeRepositoryS3Bucket
    #################################### SNS Topic and Subscription#################################
    - Label: 
        default: "SNS Configuration:"
      Parameters: 
      - SNSTopicBaseName
      - SNSTopicDisplayName
      - SNSSubscriptionEmail
    #################################### Step Function #############################################
    - Label:
        default: "Step Function Configuration:"
      Parameters:
      - StepFunctionExecutionRoleBaseName
      - StepFunctionExecutionPolicyBaseName
      - StepFunctionBaseName
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## KMS Key ###################################################
      KmsMasterKeyAlias:
        default: "KMS Key Alias."
      KmsMasterKeyId:
        default: "KMS Key Id."
      #################################### Code Repository Bucket ####################################
      CodeRepositoryS3Bucket:
        default: "Code Repository S3 Bucket."
      ################################## SNS Topic and Subscription#################################
      SNSTopicBaseName:
        default: "Result Notification SQS Topic Name."
      SNSTopicDisplayName:
        default: "Result Notification SQS Topic Diaplay Name."
      SNSSubscriptionEmail:
        default: "Result Notification SQS Subscription Email."
      ################################## Step Function #############################################
      StepFunctionBaseName:
        default: "Step Function base name."
      StepFunctionExecutionRoleBaseName:
        default: "Step Function Role Name."
      StepFunctionExecutionPolicyBaseName:
        default: "Step Function Policy Name."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: clover
    Description: "The Project Name for which the custom resource will be used."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### KMS #######################################################
  KmsMasterKeyAlias:
    Default: "SB-KMS"
    Description: "The KMS Master Key Alias to be used for server side encryption."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash."
  KmsMasterKeyId:
    Default: "arn:aws:kms:us-east-1:807724355529:key/e4c733c5-9fbe-4a90-bda1-6f0362bc9b89"
    Description: "The KMS Key Id used for encryption."
    Type: String
    MinLength: 75
    MaxLength: 175
    AllowedPattern: "[a-z0-9-/:]*"
    ConstraintDescription: "The length of the KMS Key Id should be 75 and must be a valid KMS Key Arn."
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  StackName:
    Default: ""
    Description: "The name of the stack which created the resource"
    Type: String  
  ###################################### Code Repository S3 Bucket #################################
  CodeRepositoryS3Bucket:
    Default: subhamay-projects-repository-us-east-1
    Description: "S3 Bucket Storing The Lambda Code."
    Type: String
    MinLength: 10
    MaxLength: 63
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 63, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  ################################## VPC Cidr Block ################################################
  VpcCidrBlock:
    Type: String
    Description: VPC CIDR Range
    Default: 10.0.0.0/16
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
  ################################## Subnet Cidr Block #############################################
  PublicSubnet1ACidrBlock:
    Type: String
    Description: CidrBlock for Public 1A within the VPC.
    Default: 10.0.1.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
  PublicSubnet1BCidrBlock:
    Type: String
    Description: CidrBlock for Public 1B within the VPC.
    Default: 10.0.2.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
  PrivateSubnet1ACidrBlock:
    Type: String
    Description: CidrBlock for Private 1B within the VPC.
    Default: 10.0.3.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
  PrivateSubnet1BCidrBlock:
    Type: String
    Description: CidrBlock for Private 1B within the VPC.
    Default: 10.0.4.0/24
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
  ###################################### SNS Topic #################################################
  SNSTopicBaseName:
    Default: "sns-topic"
    Description: "The base name of the SNS Topic."
    Type: String
    MinLength: 8
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 8 and 40, must contain only alphanumeric character and dash (-).
  SNSTopicDisplayName:
    Default: "SNS Topic name for sending result notification"
    Description: "The Base Name of the SNS Topic."
    Type: String
    MinLength: 10
    MaxLength: 100
    AllowedPattern: "[a-zA-Z0-9-. _]*"
    ConstraintDescription: "The length should be between 30 and 200, must alphanumeric character, space, dot and underscore."
  SNSSubscriptionEmail:
    Default: "subhamay.aws@mailinator.com"
    Description: "The subscription email for the SNS Topic."
    Type: String
    MinLength: 10
    MaxLength: 100
  ###################################### Step Function #############################################
  StepFunctionExecutionRoleBaseName:
    Default: sf-execution-role
    Description: Step Function execution IAM role name.
    Type: String
    MinLength: 5
    MaxLength: 50
    AllowedPattern: "[a-zA-Z-]*"
    ConstraintDescription: The length should be between 5 and 50, , must contain only lowercase letters,numbers and hyphen (-).
  StepFunctionExecutionPolicyBaseName:
    Default: sf-execution-policy
    Description: Step Function execution IAM policy name
    Type: String
    MinLength: 5
    MaxLength: 50
    AllowedPattern: "[a-zA-Z-]*"
    ConstraintDescription: The length should be between 5 and 50, must contain only lowercase letters,numbers and hyphen (-).
  StepFunctionBaseName:
    Default: state-machine
    Description: Step Function base name.
    Type: String
    MinLength: 5
    MaxLength: 50
    AllowedPattern: "[a-zA-Z-]*"
    ConstraintDescription: The length should be between 5 and 50, must contain only lowecase letters, numbers and hyphen (-).

Resources:
  ###################################### VPC #######################################################
  CloverVPCStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub 'https://${CodeRepositoryS3Bucket}.s3.amazonaws.com/${GitHubRepository}/cft/nested-stacks/vpc-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GitHubRef: !Ref GitHubRef
        GitHubURL: !Ref GitHubURL
        GitHubWFRunNumber: !Ref GitHubWFRunNumber
        GitHubSHA: !Ref GitHubSHA
        GitHubRepository: !Ref GitHubRepository
        CiBuild: !Ref CiBuild
        StackName: !Ref StackName
        VpcCidrBlock: !Ref VpcCidrBlock
        PublicSubnet1ACidrBlock: !Ref PublicSubnet1ACidrBlock 
        PublicSubnet1BCidrBlock: !Ref PublicSubnet1BCidrBlock
        PrivateSubnet1ACidrBlock: !Ref PrivateSubnet1ACidrBlock
        PrivateSubnet1BCidrBlock: !Ref PrivateSubnet1BCidrBlock
      TimeoutInMinutes: 5
  ###################################### Security Group ################################################################
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Sub 'https://${CodeRepositoryS3Bucket}.s3.amazonaws.com/${GitHubRepository}/cft/nested-stacks/security-group-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GitHubRef: !Ref GitHubRef
        GitHubURL: !Ref GitHubURL
        GitHubWFRunNumber: !Ref GitHubWFRunNumber
        GitHubSHA: !Ref GitHubSHA
        GitHubRepository: !Ref GitHubRepository
        CiBuild: !Ref CiBuild
        StackName: !Ref StackName
        VPCId: !GetAtt CloverVPCStack.Outputs.VpcId
        SecurityGroupName: 'clov-sg'
        SecurityGroupDescription: "SSH Security Group."
      TimeoutInMinutes: 5
  ###################################### IAM Roles and Policies ####################################
  CloverIAMRole:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CodeRepositoryS3Bucket}.s3.amazonaws.com/${GitHubRepository}/cft/nested-stacks/iam-role-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GitHubRepository: !Ref GitHubRepository
        GitHubRef: !Ref GitHubRef
        GitHubURL: !Ref GitHubURL
        GitHubWFRunNumber: !Ref GitHubWFRunNumber
        GitHubSHA: !Ref GitHubSHA
        StackName: !Ref StackName
        CiBuild: !Ref CiBuild
        StepFunctionBaseName: !Ref StepFunctionBaseName
        StepFunctionExecutionRoleBaseName: !Ref StepFunctionExecutionRoleBaseName
        StepFunctionExecutionPolicyBaseName: !Ref StepFunctionExecutionPolicyBaseName
        SNSTopicBaseName: !Ref SNSTopicBaseName
        KmsMasterKeyId: !Ref KmsMasterKeyId
      TimeoutInMinutes: 15
  ###################################### SNS Topic with Subscription ###############################
  CloverSNSTopic:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CodeRepositoryS3Bucket}.s3.amazonaws.com/${GitHubRepository}/cft/nested-stacks/sns-stack.yaml'
      Parameters:  
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GitHubRef: !Ref GitHubRef
        GitHubURL: !Ref GitHubURL
        GitHubWFRunNumber: !Ref GitHubWFRunNumber
        GitHubSHA: !Ref GitHubSHA
        GitHubRepository: !Ref GitHubRepository
        CiBuild: !Ref CiBuild
        StackName: !Ref StackName
        SNSTopicBaseName: !Ref SNSTopicBaseName
        SNSTopicDisplayName: !Ref SNSTopicDisplayName
        SNSSubscriptionEmail: !Ref SNSSubscriptionEmail
        KmsMasterKeyAlias: !Ref KmsMasterKeyAlias
      TimeoutInMinutes: 15
  ###################################### State Machine #############################################
  CloverStateMachineLogGroup:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::Logs::LogGroup
    Properties: 
      KmsKeyId: !Ref KmsMasterKeyId
      LogGroupName: !Sub '/aws/states/${ProjectName}-${StepFunctionBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      RetentionInDays: 14
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: CodeRepositoryS3Bucket
        Value: !Ref CodeRepositoryS3Bucket
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
      - Key: StackName
        Value: !Ref StackName
  CloverStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${ProjectName}-${StepFunctionBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      LoggingConfiguration:
        Level: ALL
        IncludeExecutionData: True
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt CloverStateMachineLogGroup.Arn
      DefinitionS3Location:
        Bucket: !Ref CodeRepositoryS3Bucket
        Key: !Sub '${GitHubRepository}/state-machine/${ProjectName}-state-machine.asl.json'
      DefinitionSubstitutions:
        SNSTopicArn: !GetAtt CloverSNSTopic.Outputs.SNSTopicArn
      RoleArn: !GetAtt CloverIAMRole.Outputs.StepFunctionExecutionRoleArn
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: CodeRepositoryS3Bucket
        Value: !Ref CodeRepositoryS3Bucket
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
      - Key: StackName
        Value: !Ref StackName
Outputs:
  CloverPublicSubnet1AId:
    Description: Public Subnet-1A Id
    Value: !GetAtt CloverVPCStack.Outputs.PublicSubnet1AId
  CloverPublicSubnet1BId:
    Description: Public Subnet-1B Id
    Value: !GetAtt CloverVPCStack.Outputs.PublicSubnet1BId
  CloverPrivateSubnet1AId:
    Description: Public Subnet-1A Id
    Value: !GetAtt CloverVPCStack.Outputs.PrivateSubnet1AId
  CloverPrivateSubnet1BId:
    Description: Public Subnet-1B Id
    Value: !GetAtt CloverVPCStack.Outputs.PrivateSubnet1BId
  CloverVpcId:
    Description: Custom Vpc Id
    Value: !GetAtt CloverVPCStack.Outputs.VpcId
  CloverCustomResourceLambdaIAMRoleArn:
    Description:  Custom Resource Lambda IAM Role Arn
    Value: !GetAtt CloverVPCStack.Outputs.CustomResourceLambdaIAMRoleArn
  CloverCustomResourceLambdaFunctionArn:
    Description: Custom Resource Lambda Arn
    Value: !GetAtt CloverVPCStack.Outputs.CustomResourceLambdaFunctionArn
  CloverVPCMainRouteTableId:
    Description: Custom VPC Main Route Table Id
    Value: !GetAtt CloverVPCStack.Outputs.VPCMainRouteTableId
  CloverStepFunctionExecutionRoleArn:
    Description: Clover Step Function Execution Role Arn.
    Value: !GetAtt CloverIAMRole.Outputs.StepFunctionExecutionRoleArn
  CloverSNSTopicArn:
    Description: Report Result SNS Topic Arn
    Value: !GetAtt CloverSNSTopic.Outputs.SNSTopicArn
  CloverSNSSubscriptionArn:
    Description: SNS Subscription Arn
    Value: !GetAtt CloverSNSTopic.Outputs.SNSSubscriptionArn
  CloverStepFunctionLogGroupArn:
    Description: Step Function Log Group Arn
    Value: !GetAtt CloverStateMachineLogGroup.Arn
  CloverStepFunctionArn: 
    Description: Step Function Arn
    Value: !Ref CloverStateMachine


